### ISSUE TITLE
Potential key leak in Simple CI/CD from Github To AWS S3 for a snake game.

### ISSUE THREAD

**Issue by fireball787b** [harish0x/AWS_Learning-CD-GithubtoS3#1]
https://github.com/harish0x/AWS_Learning-CD-GithubtoS3/blob/7de1b0f46610d6357ae39577511741ba4b9c4ba9/.github/workflows/deploys3.yml#L10

Hello , good morning.

Sorry to write you here but I tried to send you a PM on linkedin but i'm not allowed :(
I've checked your post on https://harishankar.me/blog/Simple-CI-CD-Deploying-in-S3 and I think there may be a leak in the Retrieve access keys section: https://harishankar.me/assets/img/snake-game/key.png
In this case, the keys are being exposed publicly but I'm not sure if these are the ones you are currently using or not, if that's the case, i just wanted to let you know.

On the other hand, great work and keep going!

Best regards

**Comment by harish0x** [comment]
Hi ,

Thank you for reaching out and bringing this to my attention. I appreciate your diligence in noticing potential security vulnerabilities.

Regarding the access keys displayed in the screenshot you mentioned, I want to reassure you that those keys were created specifically for the purpose of the project and were not intended for any production or sensitive environments. However, I understand the importance of maintaining good security practices, and I've already taken action to remove those keys from any public access.

Thank you once again for taking the time to reach out and for your support.

Best regards
